### ISSUE TITLE
Extra simple for users. Use sed and awk for file manipulation

### ISSUE THREAD

**Issue by twobob** [amrrs/llama-4bit-colab#1]
To remove the manual step
elide the last line.
`!sed -i '$d' requirements.txt` 
and append your new one using awk.. 
see [stack 12141938/how-to-detect-the-last-line-in-awk-before-end](https://stackoverflow.com/questions/12141938/how-to-detect-the-last-line-in-awk-before-end) 
``!awk '{ print $0; while ( getline == 1 ) { print $0; } print "git+https://github.com/zphang/transformers@660dd6e2bbc9255aacd0e60084cf15df1b6ae00d#egg=transformers"; } ' requirements.txt > tmp && cp tmp requirements.txt && rm tmp``

something of this order can remove the manual step

**Comment by twobob** [comment]
https://colab.research.google.com/github/twobob/llama-4bit-colab/blob/patch-1/LLaMA_4_bit_on_Google_Colab.ipynb#scrollTo=1DEWtsdzd_Co like that

**Comment by tiagorangel2011** [comment]
**Not working** :(
```
# Latest step, step 6
Traceback (most recent call last):
  File "/content/GPTQ-for-LLaMa/llama_inference.py", line 108, in <module>
    model = load_quant(args.model, args.load, args.wbits)
  File "/content/GPTQ-for-LLaMa/llama_inference.py", line 27, in load_quant
    from transformers import LlamaConfig, LlamaForCausalLM 
ImportError: cannot import name 'LlamaConfig' from 'transformers' (/usr/local/lib/python3.9/dist-packages/transformers/__init__.py)

```

**Comment by twobob** [comment]
> **Not working** :(
> 
> ```
> # Latest step, step 6
> Traceback (most recent call last):
>   File "/content/GPTQ-for-LLaMa/llama_inference.py", line 108, in <module>
>     model = load_quant(args.model, args.load, args.wbits)
>   File "/content/GPTQ-for-LLaMa/llama_inference.py", line 27, in load_quant
>     from transformers import LlamaConfig, LlamaForCausalLM 
> ImportError: cannot import name 'LlamaConfig' from 'transformers' (/usr/local/lib/python3.9/dist-packages/transformers/__init__.py)
> ```

upstream added a newline the the end of file.
Fixed.

**Comment by twobob** [comment]
![image](https://user-images.githubusercontent.com/915232/225996272-9e82e0ad-99c7-4102-98eb-a799db1b27d0.png)

**Comment by twobob** [comment]
hmm yeah. ah well it doesn't look like is getting much support anyway. Closed
